### PR TITLE
Add Asset Locked and Status Transition Labels

### PR DESCRIPTION
**Pull request by iammer**

### CODE REVIEW

**Comment by iammer** [comment]
@jeremywen, Can you review when you have a chance?  This is for 2 additional fields the TRC LineHub people requested.

**Comment by jeremywen** [comment]
Looks good.  What's a transition?

**Comment by iammer** [comment]
@jeremywen, I wasn't sure what to call it.  It is the label on the connecting lines between events on the workflow.  It defaults to Possible or Next (and I didn't even know it was possible to change it until the LineHub people showed me).  They are using it for something (i.e. that have something automated that gets the project via API then advances it based on the label and some external criteria).

**Comment by jeremywen** [comment]
Oh ya, I remember adding that feature in the beginning of the work flow editor.  I didn't think people really used it much.  I guess somebody does.  I think I called it a connection label but transition works.

**Pull request merged**
