### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kattrali**

### CODE REVIEW

**Comment by spidaMikeFord** [comment]
LOL! How are you doing?

**Comment by kattrali** [comment]
haha not too bad :smile:

**Comment by spidaMikeFord** [comment]
So what everyone wants to know is *why* were you reading Tim's misspelled documentation? :-)

**Comment by kattrali** [comment]
The mystery is better than the explanation! I was having a chat about bad `JSONObject` Java libraries with the android guy at work, and wondered what SPIDA uses now. Then I skimmed the repo and spotted a typo that was obviously @tgsoverly. The rest was civic duty.

**Comment by spidaMikeFord** [comment]
I think we still import three different libraries for some reason or another :( We did all of our work using net.sf, because it can do some auto-conversion of xml...then found out that the validator we were using... just kind of ignored half of the standard. The new validator uses something else internally. I don't like to think about the conversions everything goes through right now. The validation itself is pretty decent, though.

**Comment by spidaMikeFord** [comment]
I like to think of cleaning up Tim's spelling as job security.

**Comment by kattrali** [comment]
Hahahaha. And thanks for the info!

**Comment by spidaMikeFord** [comment]
Thanks for the code fix! Stop by Jordan's next time you're in Columbus. I want to hear about your wild post-SPIDA adventures!

**Comment by kattrali** [comment]
Mmmm potato skins. Deal!

**Pull request merged**
